ARG BASE_CONTAINER=golang:1.21-bullseye
FROM ${BASE_CONTAINER} as builder
ARG BASE_CONTAINER

# Taken from https://dev.to/karanpratapsingh/dockerize-your-go-app-46pp

# Fix DL4006
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER root

ENV DEBIAN_FRONTEND noninteractive

RUN \
    apt-get update \
    && apt-get install -y --no-install-recommends \
    fonts-droid-fallback \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN dpkg -l
