-- =====================================================================================
-- jetsapi.agent_audit -- GENERATED by `jets-agentic generate`. DO NOT EDIT.
-- Source: tools/jets_agentic/jets_agentic/model.py, model version 0.1.0.
-- The agentic audit store's system of record (plan section 7.2): intent, decision and
-- outcome rows appended per agent run, append-only by trigger, hash-chained per run.
-- Statements are separated by `-- stmt` markers; jets/agentic/audit.InstallSchema
-- executes them. The existing zap audit logger stays as the CloudWatch mirror.
-- =====================================================================================
-- stmt
CREATE SCHEMA IF NOT EXISTS jetsapi;
-- stmt
CREATE TABLE IF NOT EXISTS jetsapi.agent_audit (
  key         bigserial PRIMARY KEY,
  -- correlates to jetsa:AgentRun.jetsa:run_id (the entity's key field)
  run_id      text NOT NULL,
  seq         integer NOT NULL,
  event_type  text NOT NULL
              CONSTRAINT agent_audit_event_type_ck
              CHECK (event_type IN ('intent', 'tool_call', 'decision', 'outcome', 'approval', 'error')),
  -- agent identity or user_email, as jetsa:ApprovalEvent.jetsa:actor
  actor       text NOT NULL,
  -- AutonomyTier at the time of the event; null when the event carries none
  tier        text
              CONSTRAINT agent_audit_tier_ck
              CHECK (tier IS NULL OR tier IN ('T0', 'T1', 'T2', 'T3', 'T4')),
  tool_name   text,
  payload     jsonb NOT NULL,
  prev_hash   bytea,
  row_hash    bytea,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (run_id, seq)
);
-- stmt
CREATE OR REPLACE FUNCTION jetsapi.agent_audit_chain() RETURNS trigger AS $$
BEGIN
  SELECT coalesce(max(seq), 0) + 1 INTO NEW.seq
    FROM jetsapi.agent_audit WHERE run_id = NEW.run_id;
  SELECT row_hash INTO NEW.prev_hash
    FROM jetsapi.agent_audit WHERE run_id = NEW.run_id AND seq = NEW.seq - 1;
  NEW.created_at := coalesce(NEW.created_at, now());
  NEW.row_hash := sha256(convert_to(
    NEW.run_id || E'\x1f' ||
    NEW.seq::text || E'\x1f' ||
    NEW.event_type || E'\x1f' ||
    NEW.actor || E'\x1f' ||
    coalesce(NEW.tier, '') || E'\x1f' ||
    coalesce(NEW.tool_name, '') || E'\x1f' ||
    NEW.payload::text || E'\x1f' ||
    to_char(NEW.created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"') || E'\x1f' ||
    coalesce(encode(NEW.prev_hash, 'hex'), ''),
    'UTF8'));
  RETURN NEW;
END $$ LANGUAGE plpgsql;
-- stmt
DROP TRIGGER IF EXISTS agent_audit_chain ON jetsapi.agent_audit;
-- stmt
CREATE TRIGGER agent_audit_chain
  BEFORE INSERT ON jetsapi.agent_audit
  FOR EACH ROW EXECUTE FUNCTION jetsapi.agent_audit_chain();
-- stmt
CREATE OR REPLACE FUNCTION jetsapi.agent_audit_immutable() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'jetsapi.agent_audit is append-only: % is not permitted; outcomes are appended as new rows, never as updates (plan section 7.2)', TG_OP;
END $$ LANGUAGE plpgsql;
-- stmt
DROP TRIGGER IF EXISTS agent_audit_immutable ON jetsapi.agent_audit;
-- stmt
CREATE TRIGGER agent_audit_immutable
  BEFORE UPDATE OR DELETE OR TRUNCATE ON jetsapi.agent_audit
  FOR EACH STATEMENT EXECUTE FUNCTION jetsapi.agent_audit_immutable();
-- stmt
REVOKE UPDATE, DELETE, TRUNCATE ON jetsapi.agent_audit FROM PUBLIC;
-- stmt
-- The run the audit store correlates to. It is here rather than in a file of
-- its own because the two are one subsystem installed by one call: agent_audit
-- has no meaning without the run its run_id names, and a separate migration
-- could leave one present and the other absent.
--
-- Unlike agent_audit this table is NOT append-only. A run is written once
-- before anything acts (the write-before-act intent, plan section 7.2) and
-- updated once when it ends, with its outcome and what it spent. That is the
-- division the audit store depends on: the run row is mutable state and the
-- audit rows are the immutable record of how it got there, so a lost update
-- here costs a summary while the trail behind it stays intact.
CREATE TABLE IF NOT EXISTS jetsapi.agent_run (
  run_id                           text PRIMARY KEY,
  agent_id                         text NOT NULL,
  agent_version                    text NOT NULL,
  model_id                         text NOT NULL,
  prompt_version                   text NOT NULL,
  tier                             text NOT NULL,
  started_at                       timestamp with time zone NOT NULL,
  ended_at                         timestamp with time zone,
  run_status                       text,
  triggered_by                     text,
  domain_model_version             text NOT NULL,
  iteration_cap                    bigint NOT NULL,
  wall_clock_cap_seconds           bigint NOT NULL,
  token_spend                      bigint,
  CONSTRAINT agent_run_tier_ck CHECK (tier IN ('T0', 'T1', 'T2', 'T3', 'T4'))
);
-- stmt
-- What a run proposes. Phase 1 writes one on success and writes nothing to git:
-- staged branch writes are the analysis's "Write - staged" class and arrive
-- with the Phase-2 approval screens, because a copilot that can commit before
-- anyone can review the commit has the supervision layer in the wrong order.
--
-- Note what `draft` means here. Appendix A.2.10 requires generated_tests,
-- affected_pipelines and the impact analysis, and a Phase-1 authoring run has
-- none of them - it produced one transformation, not a change set with tests
-- and a blast radius. Those columns are NOT NULL because the model marks the
-- fields required, and a draft carries empty arrays rather than nulls: honest
-- about having nothing, and distinguishable from a proposal that was never
-- asked. The approval lifecycle fills them before the proposal may leave
-- draft, which is what the state is for.
CREATE TABLE IF NOT EXISTS jetsapi.change_proposal (
  proposal_id                      text PRIMARY KEY,
  trigger                          text NOT NULL,
  trigger_ref                      text,
  affected_pipelines               text[] NOT NULL,
  code_diff_repository             text,
  code_diff_branch                 text,
  code_diff_files_changed          text[],
  code_diff_lines_added            bigint,
  code_diff_lines_removed          bigint,
  rationale                        text,
  assumptions_made                 text[],
  generated_tests                  text[] NOT NULL,
  ci_result_status                 text,
  ci_result_tests_run              bigint,
  ci_result_tests_failed           bigint,
  impact_affected_assets           text[] NOT NULL,
  impact_clinical_relevance_touched boolean NOT NULL,
  approval_state                   text NOT NULL,
  proposal_model_version           text NOT NULL,
  CONSTRAINT change_proposal_approval_state_ck CHECK (approval_state IN ('draft', 'validated', 'agent_reviewed', 'awaiting_human_approval', 'approved', 'approved_with_modification', 'rejected', 'superseded', 'deployed'))
);
-- stmt
-- Who decided what, and from which state to which. The supervision seam of
-- section 7.2, emitted for the first time at K.1.
--
-- **This table is the typed half of a record whose other half is an audit
-- event, and the two are written in one transaction.** jetsapi.agent_audit
-- carries an `approval` event type and has since Phase 0, which is what makes
-- the decision tamper-evident: hash-chained, append-only, ordered within its
-- run. What it cannot carry is structure. Its columns are actor and tier; the
-- subject, the two states and the rationale would live in `payload` jsonb,
-- where `from_state` is unconstrained while change_proposal.approval_state
-- three tables up is CHECKed against the same vocabulary. Recording a
-- transition less strictly than the state it produces is the asymmetry this
-- table removes.
--
-- Like agent_run and unlike agent_audit it is not append-only by trigger, and
-- unlike agent_run it is never updated either: a decision is a new row
-- referencing the same subject, which is the entity's own docstring and the
-- reason outcomes are appended rather than mutated.
--
-- run_ref is the originating run, not the approver's session. A proposal is
-- approved after the run that produced it has ended, so this table and the
-- chain both grow past agent_run.ended_at. That is intended: the approval is
-- part of the run's story, and there is no seal to violate - nothing closes a
-- chain.
CREATE TABLE IF NOT EXISTS jetsapi.approval_event (
  approval_event_id                text PRIMARY KEY,
  run_ref                          text NOT NULL,
  subject_ref                      text NOT NULL,
  from_state                       text NOT NULL,
  to_state                         text NOT NULL,
  actor                            text NOT NULL,
  tier_at_event                    text NOT NULL,
  decided_at                       timestamp with time zone NOT NULL,
  decision_rationale               text,
  CONSTRAINT approval_event_from_state_ck CHECK (from_state IN ('draft', 'validated', 'agent_reviewed', 'awaiting_human_approval', 'approved', 'approved_with_modification', 'rejected', 'superseded', 'deployed')),
  CONSTRAINT approval_event_to_state_ck CHECK (to_state IN ('draft', 'validated', 'agent_reviewed', 'awaiting_human_approval', 'approved', 'approved_with_modification', 'rejected', 'superseded', 'deployed')),
  CONSTRAINT approval_event_tier_ck CHECK (tier_at_event IN ('T0', 'T1', 'T2', 'T3', 'T4'))
);
-- stmt
-- Answering "who approved proposal X" and "what happened to it" without a
-- jsonb scan is the whole reason the typed half exists.
CREATE INDEX IF NOT EXISTS approval_event_subject_idx
  ON jetsapi.approval_event (subject_ref, decided_at);
-- stmt
CREATE INDEX IF NOT EXISTS approval_event_run_idx
  ON jetsapi.approval_event (run_ref);
-- stmt
-- What a deterministic detector observed, emitted at N.2 (phase-3 plan section 12).
--
-- **This table is here because `$as_table` is not persistence.** The Anomaly entity
-- carries jr_as_table = True, which makes it a table in the JetRules domain model and
-- says nothing about Postgres. I-24 was raised when exactly that confusion left
-- agent_run and change_proposal modelled and unwritable, and was resolved by emitting
-- both from this generator. Anomaly is the third application of that resolution, and
-- the first where the two halves were done in one change rather than two phases apart.
--
-- Unlike agent_audit this table is not append-only by trigger, and unlike agent_run it
-- is not updated: a detector's observation is a fact about one run at one instant.
-- Re-running a detector over the same worker produces a second row, and that is
-- intended - the anomaly_detector_ref column is what tells two generations of a
-- detector apart.
--
-- Section 12.2 fixes what each column can hold; three of the schema's own required
-- properties are nullable here because four of the six derivable rows are within-run
-- predicates with no range and no magnitude (I-126). The CHECK constraints carry the
-- three vocabularies, two of which extend the proposal's Appendix A.2.6 with the rows
-- and grains JetStore's execution record actually has (I-127).
--
-- anomaly_confounders is a text[] with a containment CHECK rather than a child table.
-- The list is small, closed and read whole, which is the same argument the array
-- columns above rest on; `<@` is what constrains an array against a vocabulary, since
-- a column CHECK cannot reach inside one element at a time.
CREATE TABLE IF NOT EXISTS jetsapi.anomaly (
  anomaly_id                       text PRIMARY KEY,
  detected_at                      timestamp with time zone NOT NULL,
  anomaly_session_id               text NOT NULL,
  anomaly_subject_type             text NOT NULL,
  anomaly_subject_ref              text NOT NULL,
  anomaly_signal_type              text NOT NULL,
  anomaly_observed_value           text NOT NULL,
  anomaly_expected_min             text,
  anomaly_expected_max             text,
  anomaly_expected_basis           text NOT NULL,
  anomaly_deviation_magnitude      double precision,
  anomaly_confounders              text[] NOT NULL,
  anomaly_detector_ref             text NOT NULL,
  CONSTRAINT anomaly_signal_type_ck CHECK (anomaly_signal_type IN ('volume', 'freshness', 'schema', 'distribution', 'rule_breach', 'cost', 'duration', 'rejection_rate', 'cardinality', 'referential', 'step_regression', 'worker_stall', 'arrival')),
  CONSTRAINT anomaly_subject_type_ck CHECK (anomaly_subject_type IN ('feed', 'pipeline', 'stage', 'run', 'table', 'column', 'worker', 'edge')),
  CONSTRAINT anomaly_confounders_ck
             CHECK (anomaly_confounders <@ ARRAY['parse_errors_only', 'parquet_input', 'on_error_drop', 'max_input_count', 'sampling_cap', 'device_writer_output', 'merge_row_count_unknown', 'step_label_ambiguous', 'stall_cause_unknown', 'cross_step_join_unavailable', 'history_truncated', 'no_physical_location', 'stage_prefix_reused', 'location_aimed_not_reached']::text[])
);
-- stmt
-- "Which anomalies did this run produce", which is how a triage step reaches them, and
-- "what has this detector been saying lately", which is how a false-positive rate is
-- read off. Neither is answerable from the primary key.
CREATE INDEX IF NOT EXISTS anomaly_session_idx
  ON jetsapi.anomaly (anomaly_session_id, detected_at);
-- stmt
CREATE INDEX IF NOT EXISTS anomaly_detector_idx
  ON jetsapi.anomaly (anomaly_detector_ref, detected_at);
-- stmt
-- What triage concluded, emitted at AB.1 (phase-4 plan section 9).
--
-- **Two taxonomies, on purpose.** incident_locus is where in the execution record
-- the evidence sits -- nine values, each a predicate over jetsapi with no free-text
-- parsing -- and classification is what produced the failure, the proposal's own ten.
-- Section 9.5's reading is that the record supports the first and does not support the
-- second below the level of a hypothesis: three of the ten classes have no substrate
-- in JetStore at all and four are evidenced only coarsely. Carrying both is that
-- section's recommendation rather than this task's choice, because pruning an imported
-- model on this project's authority is the unreviewed extraction gap 2b exists to
-- prevent. Read incident_locus as evidence and classification as a claim; a report
-- that aggregates accuracy over both is the silent rescoping criterion 46 forbids.
--
-- **The grain is the session and that is a finding, not a default.** Seven tables can
-- carry evidence for an incident and session_id is the only key all seven share
-- (F202), so an incident identified below the session is one whose evidence set cannot
-- be assembled by a join. incident_step_ref and incident_shard_ref are nullable
-- because localisation is a property of an incident and not its identity: four of the
-- nine loci supply no step at all. An incident that sets incident_step_ref should
-- carry step_label_ambiguous, cpipes_step_id being a stage location rather than a step
-- identity (F52) -- which is why incident_confounders reuses the detector's vocabulary
-- rather than opening a second one that would not compare.
--
-- **incident_step_confounder_ck is the one cross-column rule in this file, and it is an
-- invariant rather than a convention.** Section 9.6 says an incident that names a step
-- must carry step_label_ambiguous, and F52's reason does not depend on which step it is:
-- cpipes_step_id is a stage location, so *any* incident naming one inherits the
-- ambiguity. That makes it checkable, and a requirement that is checkable and left to
-- prose is a requirement that goes quiet the first time nobody re-reads the plan. The
-- alternative -- leave it to AC.1 -- was rejected for that reason and not for a
-- technical one.
--
-- Note what is NOT a column: hypotheses. The domain model declares it as an object
-- property and JetRules traverses it in working memory; in Postgres the same
-- relationship is jetsapi.hypothesis.hypothesis_incident_ref, and two writable
-- statements of one fact is how they drift. The emitter drops the column by rule
-- rather than by hand -- see _table_columns.
--
-- Like anomaly and unlike agent_audit this table is not append-only by trigger, and
-- unlike anomaly it IS updated: status walks Appendix A.5's state machine, so an
-- incident row is mutable state and the audit chain is the record of how it moved.
CREATE TABLE IF NOT EXISTS jetsapi.incident (
  incident_id                      text PRIMARY KEY,
  incident_session_id              text NOT NULL,
  incident_detected_at             timestamp with time zone NOT NULL,
  incident_locus                   text NOT NULL,
  classification                   text,
  severity                         text NOT NULL,
  status                           text NOT NULL,
  incident_step_ref                text,
  incident_shard_ref               bigint,
  incident_confounders             text[] NOT NULL,
  incident_model_version           text NOT NULL,
  CONSTRAINT incident_locus_ck CHECK (incident_locus IN ('run_not_started', 'step_never_started', 'worker_not_terminated', 'worker_failed', 'sink_failed_under_completed_worker', 'rows_lost_silently', 'per_record_failures_reported', 'per_record_failures_unreportable', 'written_not_arrived')),
  CONSTRAINT incident_classification_ck
             CHECK (classification IS NULL OR classification IN ('source_delivery_failure', 'source_content_change', 'transport_failure', 'parse_failure', 'validation_breach', 'transformation_defect', 'infrastructure_failure', 'dependency_failure', 'capacity_or_cost_deviation', 'benign_variation')),
  CONSTRAINT incident_severity_ck CHECK (severity IN ('info', 'low', 'medium', 'high', 'critical')),
  CONSTRAINT incident_status_ck CHECK (status IN ('detected', 'triaged', 'diagnosed', 'remediation_proposed', 'awaiting_approval', 'remediating', 'resolved', 'verified', 'closed', 'reclassified', 'suppressed_as_benign')),
  CONSTRAINT incident_confounders_ck
             CHECK (incident_confounders <@ ARRAY['parse_errors_only', 'parquet_input', 'on_error_drop', 'max_input_count', 'sampling_cap', 'device_writer_output', 'merge_row_count_unknown', 'step_label_ambiguous', 'stall_cause_unknown', 'cross_step_join_unavailable', 'history_truncated', 'no_physical_location', 'stage_prefix_reused', 'location_aimed_not_reached']::text[]),
  CONSTRAINT incident_step_confounder_ck
             CHECK (incident_step_ref IS NULL
                    OR 'step_label_ambiguous' = ANY (incident_confounders))
);
-- stmt
-- "What happened in this run", which is how an operator reaches an incident from a
-- session id, and "what is open", which is how a supervision screen lists them.
CREATE INDEX IF NOT EXISTS incident_session_idx
  ON jetsapi.incident (incident_session_id, incident_detected_at);
-- stmt
CREATE INDEX IF NOT EXISTS incident_status_idx
  ON jetsapi.incident (status, incident_detected_at);
-- stmt
-- One ranked causal hypothesis for an incident, emitted at AB.1 with the table above.
--
-- **contradicting_evidence is NOT NULL because the model marks it required, and that
-- is the whole point of the column.** Appendix A.2.8 calls it a calibration control:
-- an agent that can omit the evidence against its own hypothesis will. Section 9.7
-- found that side has a substrate already built -- AnomalyConfounder's fourteen
-- members are the record's own statement of what a detector could not rule out -- and
-- EvidenceSource gained detector_confounder at AB.1 so a hypothesis can name it. An
-- empty array is the honest value where the agent asserts none exists; null is not.
--
-- Both evidence columns are jsonb rather than text[]. Evidence is a value object with
-- three fields and no table of its own (it is a JetsaValue, $as_table = false, on the
-- jets:State precedent), so it inlines; text[] is what the emitter's unmapped-type
-- fall-through would have produced, and it would have stored three fields as one
-- opaque string per item. That is I-128's silent widening reaching a composite, and
-- tabling this entity is what exposed it.
--
-- hypothesis_incident_ref has no foreign key, on approval_event.run_ref's precedent:
-- these tables are installed by one call and purged by session, and a constraint here
-- would order inserts that shadow mode has no reason to order. The index is what the
-- question actually needs.
CREATE TABLE IF NOT EXISTS jetsapi.hypothesis (
  hypothesis_id                    text PRIMARY KEY,
  hypothesis_incident_ref          text NOT NULL,
  cause                            text NOT NULL,
  cause_category                   text,
  confidence                       double precision NOT NULL,
  rank                             bigint NOT NULL,
  supporting_evidence              jsonb NOT NULL,
  contradicting_evidence           jsonb NOT NULL,
  CONSTRAINT hypothesis_cause_category_ck
             CHECK (cause_category IS NULL OR cause_category IN ('source_delivery_failure', 'source_content_change', 'transport_failure', 'parse_failure', 'validation_breach', 'transformation_defect', 'infrastructure_failure', 'dependency_failure', 'capacity_or_cost_deviation', 'benign_variation'))
);
-- stmt
-- "The ranking for this incident, in order", which is the only way a human reads
-- hypotheses and is not answerable from the primary key.
CREATE INDEX IF NOT EXISTS hypothesis_incident_idx
  ON jetsapi.hypothesis (hypothesis_incident_ref, rank);
-- stmt
-- A proposed corrective action, emitted at AB.2 (phase-4 plan section 12) -- **with no
-- executor, and nothing in this phase writes a row.** Criterion 47 says in terms that
-- nothing acts; what the table buys is that Phase 5's autonomy gate has a subject.
-- Section 1.4's finding is that autonomy tiers are recorded, trustworthy and gate
-- nothing, and autonomy_tier_required is the one property in the model that names the
-- authority an *action* needs rather than the authority a run had.
--
-- **remediation_reversibility_ck is Appendix A.2.9's validator rule and not this
-- project's policy.** The appendix states it: "reversibility: irreversible is rejected
-- at schema level. No irreversible remediation may be persisted at any tier (Section
-- 4.3)." So the Reversibility vocabulary carries three members -- the rule is about the
-- third -- and this table accepts two. The excluded value is read off the enum rather
-- than spelled here, so a rename moves the rule instead of quietly widening it, which
-- is the same mechanism as incident_step_confounder_ck above.
--
-- **The cost of that CHECK is worth naming beside it.** An agent that concludes the
-- only available correction is irreversible cannot record the conclusion; it can only
-- decline to propose. The record then shows nothing where a refusal happened, which is
-- a gap a supervision screen cannot display and a Phase 5 metric cannot count. Enforcing
-- the appendix's own rule is still the right call at this phase -- the alternative is a
-- table that accepts a row section 4.3 forbids -- but it is a trade rather than a free
-- guard (R-35).
--
-- Four of Appendix A.2.9's nine required properties are absent: action_type, proposed_by,
-- rationale and blast_radius. The first is the executor's dispatch key and a tier rule
-- keyed on it would be this task inventing Phase 5's gate; the others are read by a
-- screen that does not write yet. approver and approved_at are absent for a different
-- reason -- ApprovalEvent.subject_ref is documented as "the Remediation or ChangeProposal
-- being decided", so they are already a row in jetsapi.approval_event, and inlining them
-- would be two writable statements of one fact.
CREATE TABLE IF NOT EXISTS jetsapi.remediation (
  remediation_id                   text PRIMARY KEY,
  incident_ref                     text NOT NULL,
  autonomy_tier_required           text NOT NULL,
  reversibility                    text NOT NULL,
  remediation_approval_state       text NOT NULL,
  CONSTRAINT remediation_tier_ck CHECK (autonomy_tier_required IN ('T0', 'T1', 'T2', 'T3', 'T4')),
  CONSTRAINT remediation_approval_state_ck
             CHECK (remediation_approval_state IN ('draft', 'validated', 'agent_reviewed', 'awaiting_human_approval', 'approved', 'approved_with_modification', 'rejected', 'superseded', 'deployed')),
  -- Appendix A.2.9: 'irreversible' is a member of the vocabulary and is not
  -- a persistable value.
  CONSTRAINT remediation_reversibility_ck
             CHECK (reversibility IN ('fully_reversible', 'reversible_with_backfill'))
);
-- stmt
-- "What has been proposed for this incident", which is how a supervision screen reaches
-- a remediation and is not answerable from the primary key.
CREATE INDEX IF NOT EXISTS remediation_incident_idx
  ON jetsapi.remediation (incident_ref, remediation_approval_state);
-- stmt
-- One transition of one incident, emitted at AB.2 (I-276). Appendix A.5's preamble says
-- "Every transition records actor, agent version where applicable, and timestamp" and
-- then draws four machines and no entity to record one. jetsapi.approval_event is that
-- entity for ChangeProposal; this is it for Incident.
--
-- **The reason it is owed is a labelled population rather than an audit trail.** Three
-- of IncidentStatus's eleven values are adjudications rather than progress --
-- reclassified, verified, suppressed_as_benign -- so the lifecycle already carried the
-- verdicts section 11.3.1's four label-bearing metrics need. What it did not carry is
-- who reached them, and a label the measured system may have written is not a label.
--
-- **event_actor_kind is a column and not a spelling convention**, which is the one place
-- this table departs from approval_event's shape on purpose. That table's actor is "a
-- user_email or an agent identity" and leaves the two apart by the shape of the string;
-- a metric that partitions human corrections from the system's own reclassifications
-- cannot rest its denominator on a regular expression over an email address.
--
-- **classification_before and classification_after travel on the event because the
-- incident row is mutable.** A second correction overwrites the first, so the pairing
-- the metrics score would be gone. RecordIncidentTransition reads classification_before
-- out of the row inside the same statement that moves it, rather than accepting it from
-- the caller: the party being measured does not state what it is measured against.
--
-- incident_event_reclassified_ck is Appendix A.5's own sentence -- "reclassified returns
-- to triaged with a new classification and a recorded reason" -- as a cross-column rule.
-- It is the second such CHECK in this file and it fires on the same argument as the
-- first: a requirement that is checkable and left in prose goes quiet the first time
-- nobody re-reads the appendix.
--
-- event_run_ref is nullable and that is the table's one stated weakness. agent_audit's
-- run_id is an AgentRun's key, and neither a human at a screen nor a deterministic
-- triage step is an AgentRun -- Incident records no run at all, where
-- ChangeProposal.trigger_ref does, which is precisely what the approval handler reads to
-- find the chain to append to. A transition with no run is durable and attributable here
-- and is not in the hash chain (R-34).
--
-- Like incident and unlike agent_audit this table has no append-only trigger, and like
-- approval_event it is never updated: a further transition is a further row.
CREATE TABLE IF NOT EXISTS jetsapi.incident_event (
  incident_event_id                text PRIMARY KEY,
  event_incident_ref               text NOT NULL,
  from_status                      text NOT NULL,
  to_status                        text NOT NULL,
  event_actor                      text NOT NULL,
  event_actor_kind                 text NOT NULL,
  transitioned_at                  timestamp with time zone NOT NULL,
  event_run_ref                    text,
  classification_before            text,
  classification_after             text,
  transition_rationale             text,
  CONSTRAINT incident_event_from_status_ck CHECK (from_status IN ('detected', 'triaged', 'diagnosed', 'remediation_proposed', 'awaiting_approval', 'remediating', 'resolved', 'verified', 'closed', 'reclassified', 'suppressed_as_benign')),
  CONSTRAINT incident_event_to_status_ck CHECK (to_status IN ('detected', 'triaged', 'diagnosed', 'remediation_proposed', 'awaiting_approval', 'remediating', 'resolved', 'verified', 'closed', 'reclassified', 'suppressed_as_benign')),
  CONSTRAINT incident_event_actor_kind_ck CHECK (event_actor_kind IN ('human', 'agent')),
  CONSTRAINT incident_event_classification_before_ck
             CHECK (classification_before IS NULL
                    OR classification_before IN ('source_delivery_failure', 'source_content_change', 'transport_failure', 'parse_failure', 'validation_breach', 'transformation_defect', 'infrastructure_failure', 'dependency_failure', 'capacity_or_cost_deviation', 'benign_variation')),
  CONSTRAINT incident_event_classification_after_ck
             CHECK (classification_after IS NULL
                    OR classification_after IN ('source_delivery_failure', 'source_content_change', 'transport_failure', 'parse_failure', 'validation_breach', 'transformation_defect', 'infrastructure_failure', 'dependency_failure', 'capacity_or_cost_deviation', 'benign_variation')),
  CONSTRAINT incident_event_reclassified_ck
             CHECK (to_status <> 'reclassified'
                    OR (classification_after IS NOT NULL
                        AND transition_rationale IS NOT NULL))
);
-- stmt
-- "How did this incident get here, in order", which is the whole point of the table and
-- is not answerable from the primary key.
CREATE INDEX IF NOT EXISTS incident_event_incident_idx
  ON jetsapi.incident_event (event_incident_ref, transitioned_at);
-- stmt
-- "Which verdicts did people reach, and when" -- the query a labelled population is
-- counted with (plan section 10.7). Partial on the actor kind because the human rows are
-- the scarce ones and the index exists to make counting them cheap.
CREATE INDEX IF NOT EXISTS incident_event_human_verdict_idx
  ON jetsapi.incident_event (to_status, transitioned_at)
  WHERE event_actor_kind = 'human';
