-- =====================================================================================
-- jetsapi.agent_audit -- GENERATED by `jets-agentic generate`. DO NOT EDIT.
-- Source: tools/jets_agentic/jets_agentic/model.py, model version 0.1.0.
-- The agentic audit store's system of record (plan section 7.2): intent, decision and
-- outcome rows appended per agent run, append-only by trigger, hash-chained per run.
-- Statements are separated by `-- stmt` markers; jets/agentic/audit.InstallSchema
-- executes them. The existing zap audit logger stays as the CloudWatch mirror.
-- =====================================================================================
-- stmt
CREATE SCHEMA IF NOT EXISTS jetsapi;
-- stmt
CREATE TABLE IF NOT EXISTS jetsapi.agent_audit (
  key         bigserial PRIMARY KEY,
  -- correlates to jetsa:AgentRun.jetsa:run_id (the entity's key field)
  run_id      text NOT NULL,
  seq         integer NOT NULL,
  event_type  text NOT NULL
              CONSTRAINT agent_audit_event_type_ck
              CHECK (event_type IN ('intent', 'tool_call', 'decision', 'outcome', 'approval', 'error')),
  -- agent identity or user_email, as jetsa:ApprovalEvent.jetsa:actor
  actor       text NOT NULL,
  -- AutonomyTier at the time of the event; null when the event carries none
  tier        text
              CONSTRAINT agent_audit_tier_ck
              CHECK (tier IS NULL OR tier IN ('T0', 'T1', 'T2', 'T3', 'T4')),
  tool_name   text,
  payload     jsonb NOT NULL,
  prev_hash   bytea,
  row_hash    bytea,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (run_id, seq)
);
-- stmt
CREATE OR REPLACE FUNCTION jetsapi.agent_audit_chain() RETURNS trigger AS $$
BEGIN
  SELECT coalesce(max(seq), 0) + 1 INTO NEW.seq
    FROM jetsapi.agent_audit WHERE run_id = NEW.run_id;
  SELECT row_hash INTO NEW.prev_hash
    FROM jetsapi.agent_audit WHERE run_id = NEW.run_id AND seq = NEW.seq - 1;
  NEW.created_at := coalesce(NEW.created_at, now());
  NEW.row_hash := sha256(convert_to(
    NEW.run_id || E'\x1f' ||
    NEW.seq::text || E'\x1f' ||
    NEW.event_type || E'\x1f' ||
    NEW.actor || E'\x1f' ||
    coalesce(NEW.tier, '') || E'\x1f' ||
    coalesce(NEW.tool_name, '') || E'\x1f' ||
    NEW.payload::text || E'\x1f' ||
    to_char(NEW.created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"') || E'\x1f' ||
    coalesce(encode(NEW.prev_hash, 'hex'), ''),
    'UTF8'));
  RETURN NEW;
END $$ LANGUAGE plpgsql;
-- stmt
DROP TRIGGER IF EXISTS agent_audit_chain ON jetsapi.agent_audit;
-- stmt
CREATE TRIGGER agent_audit_chain
  BEFORE INSERT ON jetsapi.agent_audit
  FOR EACH ROW EXECUTE FUNCTION jetsapi.agent_audit_chain();
-- stmt
CREATE OR REPLACE FUNCTION jetsapi.agent_audit_immutable() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'jetsapi.agent_audit is append-only: % is not permitted; outcomes are appended as new rows, never as updates (plan section 7.2)', TG_OP;
END $$ LANGUAGE plpgsql;
-- stmt
DROP TRIGGER IF EXISTS agent_audit_immutable ON jetsapi.agent_audit;
-- stmt
CREATE TRIGGER agent_audit_immutable
  BEFORE UPDATE OR DELETE OR TRUNCATE ON jetsapi.agent_audit
  FOR EACH STATEMENT EXECUTE FUNCTION jetsapi.agent_audit_immutable();
-- stmt
REVOKE UPDATE, DELETE, TRUNCATE ON jetsapi.agent_audit FROM PUBLIC;
-- stmt
-- The run the audit store correlates to. It is here rather than in a file of
-- its own because the two are one subsystem installed by one call: agent_audit
-- has no meaning without the run its run_id names, and a separate migration
-- could leave one present and the other absent.
--
-- Unlike agent_audit this table is NOT append-only. A run is written once
-- before anything acts (the write-before-act intent, plan section 7.2) and
-- updated once when it ends, with its outcome and what it spent. That is the
-- division the audit store depends on: the run row is mutable state and the
-- audit rows are the immutable record of how it got there, so a lost update
-- here costs a summary while the trail behind it stays intact.
CREATE TABLE IF NOT EXISTS jetsapi.agent_run (
  run_id                           text PRIMARY KEY,
  agent_id                         text NOT NULL,
  agent_version                    text NOT NULL,
  model_id                         text NOT NULL,
  prompt_version                   text NOT NULL,
  tier                             text NOT NULL,
  started_at                       timestamp with time zone NOT NULL,
  ended_at                         timestamp with time zone,
  run_status                       text,
  triggered_by                     text,
  domain_model_version             text NOT NULL,
  iteration_cap                    bigint NOT NULL,
  wall_clock_cap_seconds           bigint NOT NULL,
  token_spend                      bigint,
  CONSTRAINT agent_run_tier_ck CHECK (tier IN ('T0', 'T1', 'T2', 'T3', 'T4'))
);
-- stmt
-- What a run proposes. Phase 1 writes one on success and writes nothing to git:
-- staged branch writes are the analysis's "Write - staged" class and arrive
-- with the Phase-2 approval screens, because a copilot that can commit before
-- anyone can review the commit has the supervision layer in the wrong order.
--
-- Note what `draft` means here. Appendix A.2.10 requires generated_tests,
-- affected_pipelines and the impact analysis, and a Phase-1 authoring run has
-- none of them - it produced one transformation, not a change set with tests
-- and a blast radius. Those columns are NOT NULL because the model marks the
-- fields required, and a draft carries empty arrays rather than nulls: honest
-- about having nothing, and distinguishable from a proposal that was never
-- asked. The approval lifecycle fills them before the proposal may leave
-- draft, which is what the state is for.
CREATE TABLE IF NOT EXISTS jetsapi.change_proposal (
  proposal_id                      text PRIMARY KEY,
  trigger                          text NOT NULL,
  trigger_ref                      text,
  affected_pipelines               text[] NOT NULL,
  code_diff_repository             text,
  code_diff_branch                 text,
  code_diff_files_changed          text[],
  code_diff_lines_added            bigint,
  code_diff_lines_removed          bigint,
  rationale                        text,
  assumptions_made                 text[],
  generated_tests                  text[] NOT NULL,
  ci_result_status                 text,
  ci_result_tests_run              bigint,
  ci_result_tests_failed           bigint,
  impact_affected_assets           text[] NOT NULL,
  impact_clinical_relevance_touched boolean NOT NULL,
  approval_state                   text NOT NULL,
  proposal_model_version           text NOT NULL,
  CONSTRAINT change_proposal_approval_state_ck CHECK (approval_state IN ('draft', 'validated', 'agent_reviewed', 'awaiting_human_approval', 'approved', 'approved_with_modification', 'rejected', 'superseded', 'deployed'))
);
-- stmt
-- Who decided what, and from which state to which. The supervision seam of
-- section 7.2, emitted for the first time at K.1.
--
-- **This table is the typed half of a record whose other half is an audit
-- event, and the two are written in one transaction.** jetsapi.agent_audit
-- carries an `approval` event type and has since Phase 0, which is what makes
-- the decision tamper-evident: hash-chained, append-only, ordered within its
-- run. What it cannot carry is structure. Its columns are actor and tier; the
-- subject, the two states and the rationale would live in `payload` jsonb,
-- where `from_state` is unconstrained while change_proposal.approval_state
-- three tables up is CHECKed against the same vocabulary. Recording a
-- transition less strictly than the state it produces is the asymmetry this
-- table removes.
--
-- Like agent_run and unlike agent_audit it is not append-only by trigger, and
-- unlike agent_run it is never updated either: a decision is a new row
-- referencing the same subject, which is the entity's own docstring and the
-- reason outcomes are appended rather than mutated.
--
-- run_ref is the originating run, not the approver's session. A proposal is
-- approved after the run that produced it has ended, so this table and the
-- chain both grow past agent_run.ended_at. That is intended: the approval is
-- part of the run's story, and there is no seal to violate - nothing closes a
-- chain.
CREATE TABLE IF NOT EXISTS jetsapi.approval_event (
  approval_event_id                text PRIMARY KEY,
  run_ref                          text NOT NULL,
  subject_ref                      text NOT NULL,
  from_state                       text NOT NULL,
  to_state                         text NOT NULL,
  actor                            text NOT NULL,
  tier_at_event                    text NOT NULL,
  decided_at                       timestamp with time zone NOT NULL,
  decision_rationale               text,
  CONSTRAINT approval_event_from_state_ck CHECK (from_state IN ('draft', 'validated', 'agent_reviewed', 'awaiting_human_approval', 'approved', 'approved_with_modification', 'rejected', 'superseded', 'deployed')),
  CONSTRAINT approval_event_to_state_ck CHECK (to_state IN ('draft', 'validated', 'agent_reviewed', 'awaiting_human_approval', 'approved', 'approved_with_modification', 'rejected', 'superseded', 'deployed')),
  CONSTRAINT approval_event_tier_ck CHECK (tier_at_event IN ('T0', 'T1', 'T2', 'T3', 'T4'))
);
-- stmt
-- Answering "who approved proposal X" and "what happened to it" without a
-- jsonb scan is the whole reason the typed half exists.
CREATE INDEX IF NOT EXISTS approval_event_subject_idx
  ON jetsapi.approval_event (subject_ref, decided_at);
-- stmt
CREATE INDEX IF NOT EXISTS approval_event_run_idx
  ON jetsapi.approval_event (run_ref);
-- stmt
-- What a deterministic detector observed, emitted at N.2 (phase-3 plan section 12).
--
-- **This table is here because `$as_table` is not persistence.** The Anomaly entity
-- carries jr_as_table = True, which makes it a table in the JetRules domain model and
-- says nothing about Postgres. I-24 was raised when exactly that confusion left
-- agent_run and change_proposal modelled and unwritable, and was resolved by emitting
-- both from this generator. Anomaly is the third application of that resolution, and
-- the first where the two halves were done in one change rather than two phases apart.
--
-- Unlike agent_audit this table is not append-only by trigger, and unlike agent_run it
-- is not updated: a detector's observation is a fact about one run at one instant.
-- Re-running a detector over the same worker produces a second row, and that is
-- intended - the anomaly_detector_ref column is what tells two generations of a
-- detector apart.
--
-- Section 12.2 fixes what each column can hold; three of the schema's own required
-- properties are nullable here because four of the six derivable rows are within-run
-- predicates with no range and no magnitude (I-126). The CHECK constraints carry the
-- three vocabularies, two of which extend the proposal's Appendix A.2.6 with the rows
-- and grains JetStore's execution record actually has (I-127).
--
-- anomaly_confounders is a text[] with a containment CHECK rather than a child table.
-- The list is small, closed and read whole, which is the same argument the array
-- columns above rest on; `<@` is what constrains an array against a vocabulary, since
-- a column CHECK cannot reach inside one element at a time.
CREATE TABLE IF NOT EXISTS jetsapi.anomaly (
  anomaly_id                       text PRIMARY KEY,
  detected_at                      timestamp with time zone NOT NULL,
  anomaly_session_id               text NOT NULL,
  anomaly_subject_type             text NOT NULL,
  anomaly_subject_ref              text NOT NULL,
  anomaly_signal_type              text NOT NULL,
  anomaly_observed_value           text NOT NULL,
  anomaly_expected_min             text,
  anomaly_expected_max             text,
  anomaly_expected_basis           text NOT NULL,
  anomaly_deviation_magnitude      double precision,
  anomaly_confounders              text[] NOT NULL,
  anomaly_detector_ref             text NOT NULL,
  CONSTRAINT anomaly_signal_type_ck CHECK (anomaly_signal_type IN ('volume', 'freshness', 'schema', 'distribution', 'rule_breach', 'cost', 'duration', 'rejection_rate', 'cardinality', 'referential', 'step_regression', 'worker_stall', 'arrival')),
  CONSTRAINT anomaly_subject_type_ck CHECK (anomaly_subject_type IN ('feed', 'pipeline', 'stage', 'run', 'table', 'column', 'worker', 'edge')),
  CONSTRAINT anomaly_confounders_ck
             CHECK (anomaly_confounders <@ ARRAY['parse_errors_only', 'parquet_input', 'on_error_drop', 'max_input_count', 'sampling_cap', 'device_writer_output', 'merge_row_count_unknown', 'step_label_ambiguous', 'stall_cause_unknown', 'cross_step_join_unavailable', 'history_truncated', 'no_physical_location', 'stage_prefix_reused', 'location_aimed_not_reached']::text[])
);
-- stmt
-- "Which anomalies did this run produce", which is how a triage step reaches them, and
-- "what has this detector been saying lately", which is how a false-positive rate is
-- read off. Neither is answerable from the primary key.
CREATE INDEX IF NOT EXISTS anomaly_session_idx
  ON jetsapi.anomaly (anomaly_session_id, detected_at);
-- stmt
CREATE INDEX IF NOT EXISTS anomaly_detector_idx
  ON jetsapi.anomaly (anomaly_detector_ref, detected_at);
