// Package audit is the agentic audit store's write path (Phase-0 item 8).
//
// jetsapi.agent_audit is the system of record: intent, decision and outcome
// rows appended per agent run, append-only by trigger, hash-chained per run.
// The schema is embedded from agent_audit.sql, which is GENERATED by
// `jets-agentic generate` from the item-1 entities — regenerate there, never
// edit the SQL.
//
// The write-before-act contract (plan section 7.2): write the intent row in
// the same transaction as the domain write it records, commit, and only then
// act. The commit is the acknowledgement — a process dying after it leaves
// the intent row durable, which is the property the apiserver's zap audit
// logger cannot give (its Sync is deferred to process exit). Outcomes are
// appended afterwards as a second row correlated by run_id, never as an
// update — that is what makes the append-only trigger tenable.
//
// The existing zap audit logger (jets/apiserver/server.go, logger_type
// "audit_log", five call sites) is deliberately retained as the CloudWatch
// mirror, for forensics and for the CWE-117 property of its JSON encoder.
// This package adds the system of record beside it; it does not replace it.
//
// One database, a separate role — not a separate database, which would break
// the same-transaction property (plan section 7.3). While the application
// connects as a superuser the REVOKE in the DDL is decorative and the
// trigger does the work; moving off superuser is a deployment
// recommendation, not a Phase-0 deliverable.
package audit

import (
	"context"
	_ "embed"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// The event taxonomy, mirroring the model's AuditEventType. The generated
// CHECK constraint is the authority; TestEventTypes asserts these constants
// against it so a drift fails the suite rather than a production insert.
const (
	EventIntent   = "intent"
	EventToolCall = "tool_call"
	EventDecision = "decision"
	EventOutcome  = "outcome"
	EventApproval = "approval"
	EventError    = "error"
)

//go:embed agent_audit.sql
var schemaSQL string

// stmtMarker separates statements in the generated DDL. The plpgsql bodies
// contain semicolons, so a `;` split (the jets_init_db.sql convention)
// cannot carry this file.
const stmtMarker = "-- stmt"

// DB is the slice of pgx that Append needs — satisfied by *pgxpool.Pool,
// *pgx.Conn and pgx.Tx alike, so the intent write can share the caller's
// transaction.
type DB interface {
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
}

// Exec is what InstallSchema needs; same implementors as DB.
type Exec interface {
	Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error)
}

// Event is one audit row. Seq, the hash chain and created_at are assigned by
// the BEFORE INSERT trigger, not by the caller.
type Event struct {
	RunId     string // correlates to jetsa:AgentRun's key
	EventType string // one of the Event* constants
	Actor     string // agent identity or user_email
	Tier      string // AutonomyTier at the time of the event; "" when none
	ToolName  string // "" when the event is not a tool call
	Payload   []byte // request/response JSON; must be non-empty valid JSON
}

// Append inserts one audit row and returns the trigger-assigned seq. Pass
// the transaction that carries the domain write the event records: for an
// intent, commit that transaction before acting — the commit is the
// acknowledgement. Concurrent appends to one run race on seq and the
// UNIQUE(run_id, seq) constraint fails one of them; events within a run are
// sequential by design, so a retry is correct.
func Append(ctx context.Context, db DB, ev *Event) (int, error) {
	var seq int
	err := db.QueryRow(ctx,
		`INSERT INTO jetsapi.agent_audit (run_id, event_type, actor, tier, tool_name, payload)
		 VALUES ($1, $2, $3, NULLIF($4, ''), NULLIF($5, ''), $6)
		 RETURNING seq`,
		ev.RunId, ev.EventType, ev.Actor, ev.Tier, ev.ToolName, ev.Payload).Scan(&seq)
	if err != nil {
		return 0, fmt.Errorf("while appending %s event for run %s: %w", ev.EventType, ev.RunId, err)
	}
	return seq, nil
}

// installLockKey is an arbitrary constant identifying this schema's install
// lock. Advisory locks share one namespace per database, so the value only has
// to be unlikely to collide with another subsystem's.
const installLockKey = 0x6a657473_61756469 // "jets" "audi"

// InstallSchema applies the embedded generated DDL. Every statement is
// idempotent (IF NOT EXISTS / OR REPLACE / DROP IF EXISTS), so it is safe on
// every `update_db -migrateDb` run, which is where it is wired.
//
// **Idempotent is not the same as concurrency-safe**, which is the part that
// bit. Two callers installing at once do not conflict over the tables — those
// are IF NOT EXISTS — but they do over CREATE OR REPLACE FUNCTION and the
// DROP/CREATE TRIGGER pair, where one transaction can drop a trigger the other
// is about to create, or deadlock on the catalog. It surfaced when a second
// package's tests began using the same database as this one's: both installed,
// and both failed intermittently.
//
// So the install takes a transaction-scoped advisory lock when the caller can
// give it a transaction, which serialises concurrent installers and releases
// on commit or rollback without a cleanup path. A caller that supplies only an
// Exec keeps the previous behaviour — that is the deployment path, where
// update_db runs alone.
func InstallSchema(ctx context.Context, db Exec) error {
	if beginner, ok := db.(interface {
		Begin(ctx context.Context) (pgx.Tx, error)
	}); ok {
		tx, err := beginner.Begin(ctx)
		if err != nil {
			return fmt.Errorf("while opening the schema-install transaction: %w", err)
		}
		defer func() { _ = tx.Rollback(ctx) }()
		if _, err := tx.Exec(ctx, "SELECT pg_advisory_xact_lock($1)", int64(installLockKey)); err != nil {
			return fmt.Errorf("while taking the schema-install lock: %w", err)
		}
		if err := installStatements(ctx, tx); err != nil {
			return err
		}
		return tx.Commit(ctx)
	}
	return installStatements(ctx, db)
}

func installStatements(ctx context.Context, db Exec) error {
	for _, stmt := range splitStatements(schemaSQL) {
		if _, err := db.Exec(ctx, stmt); err != nil {
			return fmt.Errorf("while installing agent_audit schema at %q: %w",
				strings.SplitN(strings.TrimSpace(stmt), "\n", 2)[0], err)
		}
	}
	return nil
}

// splitStatements cuts the DDL on lines that are exactly the marker — a
// substring split would also fire on the marker's mention in the header
// prose — and drops comment-only chunks.
func splitStatements(sql string) []string {
	var stmts []string
	var current []string
	flush := func() {
		stmt := strings.Join(current, "\n")
		if !onlyComments(stmt) {
			stmts = append(stmts, stmt)
		}
		current = current[:0]
	}
	for _, line := range strings.Split(sql, "\n") {
		if strings.TrimSpace(line) == stmtMarker {
			flush()
			continue
		}
		current = append(current, line)
	}
	flush()
	return stmts
}

func onlyComments(stmt string) bool {
	for _, line := range strings.Split(stmt, "\n") {
		line = strings.TrimSpace(line)
		if line != "" && !strings.HasPrefix(line, "--") {
			return false
		}
	}
	return true
}
