// Code generated by `jets-agentic generate`. DO NOT EDIT.
// Source: tools/jets_agentic/jets_agentic/model.py, model version 0.1.0.
//
// The domain model's data_classification markers, as data (AE.2, I-311).
// A property listed here carries a handling requirement that the
// agent_supervision capability does not by itself satisfy; phi.go is what
// enforces that, and TestEveryClassifiedPropertyHasARedactor is what refuses to
// let this list and that enforcement drift apart.

package audit

// DataClassifiedProperties is every property of the jets_agentic domain model
// carrying a data_classification marker, in model declaration order.
//
// **It is a list rather than a flag because the interesting failure is a second
// entry.** One marked property can be handled by hand; the moment a second is
// marked, something has to notice, and a generated list is what a test can
// compare against a redactor's coverage.
var DataClassifiedProperties = []ClassifiedProperty{
	{Entity: "Evidence", Property: "statement", Classification: "PHI"},
}
