FROM compile_ws:latest AS builder

FROM cpipes_native_lambda:latest

# Copy the compiled workspace to make a workspace-specific image
ARG WORKSPACE
ENV WORKSPACE=${WORKSPACE}

# Copy the compiled workspace to workspace-specific image
COPY --from=builder /$WORKSPACE /$WORKSPACE
