"""Emit the applicability matrix as one generated Go data file (B.17).

The plan's §5.2.2 staging: `pipes_model.go` stays hand-written (the Go struct
emitter is proven on the greenfield `jets_agentic` types first), but the cheap
80% of the benefit ships now - a single generated file carrying the matrix as
data, compiled into `compute_pipes`, for the validator and the schema overlay
to read instead of duplicating applicability knowledge in code.

The emission is claim-only and matrix-driven: per (go_struct, token), the
applicable fields with their requiredness, conditional-requirement expression,
and value range. A field key absent from a token's map is inapplicable for
that token - the same convention the Pydantic model enforces with
extra="forbid". `reflect --check` keeps the matrix synced to the model, so
this file is transitively model-true.
"""

from __future__ import annotations

import argparse
from collections import defaultdict

from .matrix_schema import NONE, Matrix, Required, YesNo

HEADER = '''// Code generated by `python -m cpipes_contract gofile` from the cpipes
// applicability matrix (tools/cpipes_contract/matrix). DO NOT EDIT.
//
// The matrix as data: per "GoStruct/token", the applicable fields with their
// requiredness, conditional-requirement expression, and value range. A field
// key absent from a token's map is inapplicable for that token. The Python
// model (tools/cpipes_contract/cpipes_model.py) is the source of truth for
// these claims; `reflect --check` keeps the matrix synced to it.

package compute_pipes

// ContractField is one field's contract for one type token.
type ContractField struct {
	// Required is true when an authored document must carry the field.
	Required bool
	// RequiredWhen carries the conditional-requirement expression
	// (e.g. "absent(expr_pos)") when the requirement is conditional.
	RequiredWhen string
	// Values is the closed value range for enum-like string fields, nil
	// when the field is free-form.
	Values []string
}

// CpipesContract maps "GoStruct/token" to the applicable fields of that
// token, keyed by json key.
var CpipesContract = map[string]map[string]ContractField{
'''


def go_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit(matrix: Matrix) -> str:
    per_token: dict[str, list] = defaultdict(list)
    for f in matrix.fields_:
        if f.applicable is not YesNo.YES:
            continue
        key = f"{f.go_struct}/{f.type_token}"
        required = f.required is Required.YES
        when = ""
        if f.required is Required.CONDITIONAL and f.required_when not in (NONE, None):
            when = f.required_when
        values: list[str] = []
        if f.values not in (NONE, None):
            values = f.values.split("|")
        per_token[key].append((f.json_key, required, when, values))

    out = [HEADER]
    for key in sorted(per_token):
        out.append(f"\t{go_str(key)}: {{")
        for json_key, required, when, values in sorted(per_token[key]):
            parts = []
            if required:
                parts.append("Required: true")
            if when:
                parts.append(f"RequiredWhen: {go_str(when)}")
            if values:
                parts.append("Values: []string{" + ", ".join(go_str(v) for v in values) + "}")
            out.append(f"\t\t{go_str(json_key)}: {{{', '.join(parts)}}},")
        out.append("\t},")
    out.append("}")
    out.append("")
    return "\n".join(out)


def run_with_matrix(args: argparse.Namespace, matrix: Matrix) -> int:
    import shutil
    import subprocess

    args.out.write_text(emit(matrix))
    if shutil.which("gofmt"):
        subprocess.run(["gofmt", "-w", str(args.out)], check=True)
    print(f"wrote {args.out}")
    return 0
