/// Serialises the field inventory of the nine user flows' forms.
///
/// The sibling of `table_config_corpus_test.dart`, and for the same reason: task
/// A.3 builds the text input and dropdown widgets, and the only trustworthy way
/// to know *which options of those widgets are actually used* is to ask the
/// running app rather than to grep the source. The table sizing was wrong three
/// times over before that lesson took — configurations share objects by
/// reference and dead code counts as live — and this is the same shape of
/// question.
///
/// **Only the field inventory, not the whole `FormConfig`.** A form also carries
/// validators, action delegates and layout, all of which are Dart closures; the
/// closures are the thing the port replaces rather than reads, so emitting them
/// is neither possible nor useful. What is emitted is what a widget has to
/// support: the field type, its key, and the options set to something other than
/// their default.
///
/// **Chrome only**, like its sibling — see that file's header, and
/// `jetstore_ai/CLAUDE.md`:
///
///     CHROME_EXECUTABLE=/usr/bin/google-chrome \
///       flutter test --platform chrome test/form_field_corpus_test.dart
library;

import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:jetsclient/modules/form_config_impl.dart';

import 'corpus_support.dart';

const corpusPath = 'jetsclient_ide/src/datatable/fixtures/form_fields.json';
const beginMarker = '===BEGIN FORM FIELD CORPUS===';
const endMarker = '===END FORM FIELD CORPUS===';

/// Update only together with the fixture. See the README beside it.
const expectedChecksum = 'fnv1a32:a87baa83';

String buildCorpus() {
  final forms = <String, dynamic>{};
  final typeCounts = <String, int>{};

  for (final key in userFlowFormKeys) {
    final config = getFormConfig(key);
    final fields = allFields(config).map((f) {
      typeCounts[f.runtimeType.toString()] =
          (typeCounts[f.runtimeType.toString()] ?? 0) + 1;
      return fieldToJson(f);
    }).toList();
    forms[key] = <String, dynamic>{
      'key': config.key,
      'title': config.title,
      'fieldCount': fields.length,
      if (config.inputFieldRowBuilder != null) 'hasRowBuilder': true,
      'fields': fields,
    };
  }

  final body = <String, dynamic>{
    'comment':
        'Generated by jetsclient/test/form_field_corpus_test.dart. '
        'Do not edit by hand — see the README beside this file.',
    'formCount': userFlowFormKeys.length,
    'fieldTypeCounts': Map.fromEntries(
      typeCounts.entries.toList()..sort((a, b) => b.value.compareTo(a.value)),
    ),
    'forms': forms,
  };
  return '${const JsonEncoder.withIndent('  ').convert(body)}\n';
}

void main() {
  test('the nine user flows define 50 form configurations', () {
    expect(userFlowFormKeys.length, 50);
    expect(
      userFlowFormKeys.toSet().length,
      userFlowFormKeys.length,
      reason: 'keys must be unique',
    );
  });

  test('every form configuration resolves', () {
    for (final key in userFlowFormKeys) {
      expect(() => getFormConfig(key), returnsNormally, reason: key);
    }
  });

  test('the field corpus the React port reads has not drifted', () {
    final corpus = buildCorpus();
    // ignore: avoid_print
    print('$beginMarker\n$corpus$endMarker');
    // ignore: avoid_print
    print('corpus checksum: ${checksum(corpus)}');

    expect(
      checksum(corpus),
      expectedChecksum,
      reason:
          'a form configuration under lib/modules/user_flows/ has changed, '
          'so $corpusPath is stale. Regenerate it and update expectedChecksum '
          'together — see the README beside the fixture.',
    );
  });
}
