/// Serialises the configuration of the screens **outside** the user flows, and
/// locks it against the JSON corpus the React port consumes.
///
/// **Why this file exists.** The three earlier corpora are all scoped to
/// `lib/modules/user_flows/` — the data-table corpus README says so in its first
/// line — and Phase 3 of the UI port migrates mostly the screens they exclude.
/// Task G3.1 is the gate that refuses to plan that work against an unmeasured
/// surface. See `projects/ui_refresh/plan/phase3_plan.md` §1.
///
/// **It enumerates the registries rather than listing keys, and that is the
/// difference from the earlier three.** They carry hand-maintained key lists,
/// which I-25 records as debt. A list cannot be checked for completeness here,
/// because the registry's key space is not one constant class: 13 of the user
/// flows' 37 table keys are `FSK` constants rather than `DTKeys`, so enumerating
/// the declared constants of any one class would silently miss a third of them.
/// The registries now expose their keys — see `screenTableConfigKeys` and the
/// four beside it — so this corpus is complete by construction rather than by
/// diligence.
///
/// **This suite only runs on the chrome platform**, for the reason every corpus
/// test here does (I-5):
///
///     CHROME_EXECUTABLE=/usr/bin/google-chrome \
///       flutter test --platform chrome test/screen_config_corpus_test.dart
///
/// To regenerate the React fixture, see
/// `jetsclient_ide/src/screens/fixtures/README.md`.
library;

import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:jetsclient/modules/data_table_config_impl.dart';
import 'package:jetsclient/modules/form_config_impl.dart';
import 'package:jetsclient/modules/workspace_ide/data_table_config.dart';
import 'package:jetsclient/modules/workspace_ide/form_config.dart';
import 'package:jetsclient/modules/workspace_ide/infer_server_admin/form_config.dart';

import 'corpus_support.dart';
import 'table_config_corpus_test.dart' show userFlowTableKeys;

/// Where the React side keeps its copy. Not read here — the browser has no
/// filesystem, which is why drift is caught by a checksum.
const corpusPath = 'jetsclient_ide/src/screens/fixtures/screen_configs.json';

const beginMarker = '===BEGIN SCREEN CONFIG CORPUS===';
const endMarker = '===END SCREEN CONFIG CORPUS===';

/// Checksum of the corpus this app currently produces.
///
/// **Update it only together with the React fixture.** A failure here means a
/// screen's configuration changed; the fix is to regenerate both, never to edit
/// this number so the test goes green.
const expectedChecksum = 'fnv1a32:b1b005ea';

/// Every table configuration the non-flow registries hold, sorted for a stable
/// diff.
List<String> screenTableKeys() =>
    <String>{...screenTableConfigKeys, ...workspaceTableConfigKeys}.toList()
      ..sort();

/// Every form configuration the non-flow registries hold, sorted.
List<String> screenFormKeys() =>
    <String>{
      ...screenFormConfigKeys,
      ...workspaceFormConfigKeys,
      ...inferServerAdminFormConfigKeys,
    }.toList()..sort();

String buildCorpus() {
  final tableKeys = screenTableKeys();
  final formKeys = screenFormKeys();

  // Reported rather than assumed. A key in both corpora would mean a screen and
  // a flow share a configuration, which changes what "migrate a flow" costs —
  // so it is measured here instead of being asserted to be empty.
  final sharedWithFlows = tableKeys.toSet().intersection(
    userFlowTableKeys.toSet(),
  );

  final tables = <String, dynamic>{};
  for (final key in tableKeys) {
    tables[key] = tableToJson(getTableConfig(key));
  }

  final forms = <String, dynamic>{};
  final fieldTypeCounts = <String, int>{};
  var fieldCount = 0;
  for (final key in formKeys) {
    final config = getFormConfig(key);
    final fields = allFields(config).map((f) {
      final type = f.runtimeType.toString();
      fieldTypeCounts[type] = (fieldTypeCounts[type] ?? 0) + 1;
      fieldCount++;
      return fieldToJson(f);
    }).toList();
    forms[key] = <String, dynamic>{
      'key': config.key,
      'title': config.title,
      'fieldCount': fields.length,
      if (config.inputFieldRowBuilder != null) 'hasRowBuilder': true,
      'fields': fields,
    };
  }

  final body = <String, dynamic>{
    'comment':
        'Generated by jetsclient/test/screen_config_corpus_test.dart. '
        'Do not edit by hand — see the README beside this file.',
    'tableCount': tableKeys.length,
    'formCount': formKeys.length,
    'fieldCount': fieldCount,
    'sharedTableKeysWithUserFlows': sharedWithFlows.toList()..sort(),
    'fieldTypeCounts': Map.fromEntries(
      fieldTypeCounts.entries.toList()
        ..sort((a, b) => b.value.compareTo(a.value)),
    ),
    'tables': tables,
    'forms': forms,
  };
  return '${const JsonEncoder.withIndent('  ').convert(body)}\n';
}

void main() {
  test('the non-flow registries are non-empty', () {
    // Guards the enumeration itself: an accessor wired to the wrong map, or a
    // registry that moved, would otherwise produce an empty corpus that passes
    // every other check in this file.
    expect(screenTableKeys(), isNotEmpty);
    expect(screenFormKeys(), isNotEmpty);
  });

  test('every enumerated key resolves to a configuration', () {
    // getTableConfig throws rather than returning null for an unknown key, so
    // this is what turns "the accessor exposed a key the lookup cannot serve"
    // into a named failure instead of a stack trace inside buildCorpus.
    for (final key in screenTableKeys()) {
      expect(() => getTableConfig(key), returnsNormally, reason: key);
    }
    for (final key in screenFormKeys()) {
      expect(() => getFormConfig(key), returnsNormally, reason: key);
    }
  });

  test('corpus is unchanged', () {
    final corpus = buildCorpus();
    // ignore: avoid_print
    print('$beginMarker\n$corpus$endMarker');
    // ignore: avoid_print
    print('corpus checksum: ${checksum(corpus)}');
    // ignore: avoid_print
    print('SUMMARY tables=${screenTableKeys().length} '
        'forms=${screenFormKeys().length}');
    expect(
      checksum(corpus),
      expectedChecksum,
      reason:
          'A screen configuration changed. Regenerate $corpusPath from this '
          'output and update expectedChecksum — both, together.',
    );
  });
}
