"""The data-classification manifest emitter (AE.2, I-311).

**A marker nothing reads is worse than no marker**, because it reads as a
control to anyone auditing the model. `Evidence.statement` has carried
`data_classification = "PHI"` since Phase 0 and it was, until this emitter, the
only property in the domain model to carry one — surviving the whole toolchain
(stripped from the JSON Schema, kept in the sidecar, emitted into every client
workspace as a rule-visible triple) and consumed by nothing. No rule matched on
it, no Go code looked at it, and the browser did not know it existed.

This module is what makes it readable by code. It emits a Go file into the
package that already holds the generated DDL, listing every marked property as
`(entity, property, classification)`, so:

- **the marker reaches the server automatically.** Marking a second property in
  `model.py` puts it in this list on the next `jets-agentic generate`, exactly
  as marking a field NOT NULL puts it in the DDL. Nothing has to remember.
- **an unhandled marker fails loudly rather than quietly.** The audit package
  keeps a redactor per entry and asserts, in both directions, that its coverage
  and this list agree — `_assert_tables_agree`'s discipline for a second kind of
  disagreement, and the reason the manifest is a *list* rather than a boolean.

**What it deliberately does not do is decide policy.** The list says which
properties are classified; what a classification obliges a reader to do is the
audit package's `PHIAccess` and the apiserver's capability check, and *who*
holds that capability is a deployment decision (Q-42). The `.jr` triple stays
where it is and is still read by no rule — this emitter adds a consumer for the
marker, not for the triple.

**Why a Go file rather than a comment in the SQL.** `Evidence` is a value object
with no table of its own; it inlines as jsonb inside `jetsapi.hypothesis`, so
there is no column to attach a `COMMENT ON` to and no CHECK to read the way
`vocabularies.test.ts` reads the status vocabulary. A generated declaration is
the shape that carries a property with no column.
"""

from __future__ import annotations

from . import model as M

# The output is committed and `generate --check` compares it, like the DDL. It
# lands beside `agent_audit.sql` in the package that consumes it, for the same
# reason: `go:embed` cannot cross package directories and neither can an
# unexported Go identifier.
_HEADER = """// Code generated by `jets-agentic generate`. DO NOT EDIT.
// Source: tools/jets_agentic/jets_agentic/model.py, model version {version}.
//
// The domain model's data_classification markers, as data (AE.2, I-311).
// A property listed here carries a handling requirement that the
// agent_supervision capability does not by itself satisfy; phi.go is what
// enforces that, and TestEveryClassifiedPropertyHasARedactor is what refuses to
// let this list and that enforcement drift apart.

package audit

// DataClassifiedProperties is every property of the jets_agentic domain model
// carrying a data_classification marker, in model declaration order.
//
// **It is a list rather than a flag because the interesting failure is a second
// entry.** One marked property can be handled by hand; the moment a second is
// marked, something has to notice, and a generated list is what a test can
// compare against a redactor's coverage.
var DataClassifiedProperties = []ClassifiedProperty{{
{entries}}}
"""


def classified_properties() -> list[tuple[str, str, str]]:
    """(entity class name, property name, classification) for every marked
    property, in `ENTITIES` order and then declaration order — the same order
    every other emitter uses, so a diff here reads like a diff there."""
    out: list[tuple[str, str, str]] = []
    for entity in M.ENTITIES:
        for fname, field in entity.model_fields.items():
            extra = field.json_schema_extra if isinstance(field.json_schema_extra, dict) else {}
            classification = extra.get("data_classification")
            if classification:
                out.append((entity.__name__, fname, classification))
    return out


def emit() -> str:
    entries = "".join(
        f'\t{{Entity: "{entity}", Property: "{prop}", Classification: "{classification}"}},\n'
        for entity, prop, classification in classified_properties()
    )
    return _HEADER.format(version=M.MODEL_VERSION, entries=entries)
