/**
 * @vitest-environment jsdom
 *
 * The incident screens (task AE.1).
 *
 * **What is worth testing here is what the screens refuse to do**, on the
 * argument `proposals.test.tsx` makes for the supervision screens beside these:
 * the refusals are the design, and they are what a later edit would undo without
 * noticing.
 *
 *  - the locus and the classification are shown together, and an unclaimed cause
 *    is words rather than a blank (R-27, I-289);
 *  - the empty list says nothing writes these tables yet, because an empty
 *    supervision queue otherwise reads as a quiet system;
 *  - an unmigrated database is reported as a deployment state and not as an
 *    outage;
 *  - contradicting evidence has a rendering when it is empty, because the empty
 *    array is an assertion (§A.2.8);
 *  - **the verdict control writes one thing and only when the server offers it**
 *    (`AJ.2`, Q-52) — the buttons come from `permittedTransitions`, a response
 *    that carries none renders read-only, and nothing else on the screen writes;
 *  - an incident with no `AgentRun` says its corrections will not be
 *    hash-chained, which is the whole visible consequence of `AB.4` (Q-32);
 *  - a withheld PHI statement is words rather than a blank, and the screen names
 *    the capability that would lift it (`AE.2`, I-311).
 *
 * The api is driven through a stub `fetch`, the way `proposals.test.tsx` does it,
 * so these exercise `ApiClient.agentic` and the wire shapes as well as the
 * components. The vocabularies these files spell are checked against the
 * generated SQL in `vocabularies.test.ts`, which needs the node environment and
 * therefore a file of its own.
 */

import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { afterEach, describe, expect, it, vi } from "vitest";

import { ApiClient } from "../api/client";
import { ApiProvider } from "../shell/capabilities";
import { NotificationsProvider, useNotifications } from "../shell/notifications";
import { IncidentScreen } from "./IncidentScreen";
import { IncidentsScreen } from "./IncidentsScreen";
import { ADJUDICATED_STATUSES, LOCUS_GLOSS, OPEN_STATUSES, vocabLabel } from "./api";
// Generated by `TestTheScreensFixtureIsAnIncidentTriageWrote` in jets/apiserver
// against a real PostgreSQL. Do not hand-edit: regenerate with UPDATE_GOLDEN=1.
import triageWritten from "./__fixtures__/triage_written_incident.json";

afterEach(cleanup);

type Reply = { status?: number; body: unknown };

async function clientWith(
  script: Record<string, Reply | ((req: Record<string, unknown>) => Reply)>,
  capabilities: string[] = ["agent_supervision"],
) {
  const sent: Record<string, unknown>[] = [];
  const fetchImpl = vi.fn(async (url: string, init?: RequestInit) => {
    if (String(url).endsWith("/login")) {
      return new Response(
        JSON.stringify({
          token: "t0",
          name: "Supervisor",
          user_email: "supervisor@example.com",
          is_admin: false,
          capabilities,
        }),
        { status: 200 },
      );
    }
    const req = JSON.parse(String(init?.body ?? "{}")) as Record<string, unknown>;
    sent.push(req);
    const entry = script[String(req["action"])];
    const reply = typeof entry === "function" ? entry(req) : entry;
    if (!reply) return new Response(JSON.stringify({ error: "no script" }), { status: 500 });
    return new Response(JSON.stringify({ token: "t1", ...(reply.body as object) }), {
      status: reply.status ?? 200,
    });
  }) as unknown as typeof fetch;
  const api = new ApiClient("", fetchImpl);
  await api.login("supervisor@example.com", "pw");
  return { api, sent };
}

/**
 * Renders the shell's banner state so a test can read it (`AJ.2`).
 *
 * The real banner belongs to `App.tsx` and is not under test here, so without
 * this the two levels the shell exposes — `error` and `status` — are invisible
 * to every test in this file. That is what a verdict's confirmation and the 409
 * recovery are: the screen's whole visible answer is a banner, and a screen
 * whose only output nothing can assert is a screen with an untested output.
 */
function NotificationProbe() {
  const { error, status } = useNotifications();
  return <div data-testid="banner">{error ?? status ?? ""}</div>;
}

function renderAt(api: ApiClient, path: string) {
  return render(
    <ApiProvider api={api}>
      <NotificationsProvider>
        <NotificationProbe />
        <MemoryRouter initialEntries={[path]}>
          <Routes>
            <Route path="/incidents" element={<IncidentsScreen api={api} />} />
            <Route path="/incidents/:incidentId" element={<IncidentScreen api={api} />} />
          </Routes>
        </MemoryRouter>
      </NotificationsProvider>
    </ApiProvider>,
  );
}

const vocabularies = {
  loci: Object.keys(LOCUS_GLOSS),
  incidentStatuses: [...OPEN_STATUSES, "resolved", "closed", ...ADJUDICATED_STATUSES],
};

/** An incident triage wrote: a locus, and no cause claimed. */
const triagedRow = {
  incidentId: "inc_1",
  sessionId: "sess_1",
  // "" is the ordinary case out of AC.1: a deterministic triage step is not an
  // AgentRun, so the incident it writes names none (AB.4).
  runRef: "",
  detectedAt: "2026-09-04T10:00:00Z",
  locus: "worker_failed",
  classification: "",
  severity: "high",
  status: "triaged",
  stepRef: "reducing00",
  shardRef: 0,
  confounders: ["step_label_ambiguous"],
  modelVersion: "0.1.0",
  hypothesisCount: 0,
};

const detail = {
  ...triagedRow,
  hypotheses: [
    {
      hypothesisId: "hyp_1",
      incidentRef: "inc_1",
      cause: "a step regressed",
      causeCategory: "",
      confidence: 0.6,
      rank: 1,
      // The two columns Q-46 added at AC.3. Carried here because the wire always
      // sends them; the tests that assert what they mean run over the generated
      // payload below rather than over this one.
      locus: "worker_failed",
      basis: { supportingCount: 1, contradictingCount: 0, evidenceability: "coarse" },
      supportingEvidence: [
        {
          statement: "step 3 ran 4x longer",
          source: "run_telemetry",
          sourceRef: "sess_1/3",
          statementRedacted: false,
        },
      ],
      contradictingEvidence: [],
    },
    {
      hypothesisId: "hyp_2",
      incidentRef: "inc_1",
      cause: "the upstream feed shrank",
      causeCategory: "source_content_change",
      confidence: 0.2,
      rank: 2,
      locus: "worker_failed",
      basis: { supportingCount: 0, contradictingCount: 1, evidenceability: "coarse" },
      supportingEvidence: [],
      contradictingEvidence: [
        {
          statement: "a sampling cap was set",
          source: "detector_confounder",
          sourceRef: "sampling_cap",
          statementRedacted: false,
        },
      ],
    },
  ],
};

/**
 * The `get_incident` envelope as the server sends it. `AE.2` widened it: the
 * redaction is reported rather than inferred from a blank statement, so a test
 * that kept sending the bare `{ incident }` would be testing a wire shape the
 * server no longer produces.
 */
const disclosed = { incident: detail, phiRedacted: false, phiCapability: "agent_phi_access", phiProperties: ["statement (PHI)"] };

describe("the incident list", () => {
  it("shows an incident and links to it", async () => {
    const { api } = await clientWith({
      list_incidents: { body: { incidents: [triagedRow], ...vocabularies } },
    });
    renderAt(api, "/incidents");
    const link = await screen.findByRole("link", { name: "inc_1" });
    expect(link.getAttribute("href")).toBe("/incidents/inc_1");
  });

  // The whole of R-27's mitigation on this screen: two columns, labelled for
  // what they are, and an unclaimed cause rendered as words. A blank cell reads
  // as data that failed to load; `classification` is nullable on purpose, so
  // that a deterministic triage step can write an incident without inventing a
  // cause (I-289).
  it("shows the locus as evidence and the cause as a claim, and says when none is claimed", async () => {
    const { api } = await clientWith({
      list_incidents: { body: { incidents: [triagedRow], ...vocabularies } },
    });
    renderAt(api, "/incidents");
    await screen.findByRole("link", { name: "inc_1" });
    expect(screen.getByRole("columnheader", { name: /Locus/ }).textContent).toContain("evidence");
    expect(screen.getByRole("columnheader", { name: /Cause/ }).textContent).toContain("claim");
    expect(screen.getByText("Worker failed")).toBeTruthy();
    expect(screen.getByText("not claimed")).toBeTruthy();
  });

  // An empty supervision queue reads as a quiet system, and this one is empty
  // because nothing writes the table — not because nothing went wrong.
  it("says why the list is empty, rather than reporting all clear", async () => {
    const { api } = await clientWith({
      list_incidents: { body: { incidents: [], ...vocabularies } },
    });
    renderAt(api, "/incidents");
    await screen.findByText("No open incidents.");
    expect(
      screen.getByText(/not evidence that nothing went wrong/),
    ).toBeTruthy();
  });

  // The adjudicated view is the read side of the only labelling instrument this
  // programme can build (I-276, plan §10.7), so the three statuses it asks for
  // are worth pinning.
  it("asks for the three adjudication statuses in the adjudicated view", async () => {
    const { api, sent } = await clientWith({
      list_incidents: { body: { incidents: [], ...vocabularies } },
    });
    renderAt(api, "/incidents");
    await screen.findByText("No open incidents.");
    fireEvent.change(screen.getByRole("combobox"), { target: { value: "adjudicated" } });
    await screen.findByText("No incident has been adjudicated.");
    expect(sent[sent.length - 1]?.["statuses"]).toEqual([
      "verified",
      "reclassified",
      "suppressed_as_benign",
    ]);
  });

  // The capability gates the request and not only the render: `DoAgenticAction`
  // logs every refusal by name, so a screen that posted anyway would write an
  // audit line for an attempt the user never made.
  it("sends nothing at all without the capability", async () => {
    const { api, sent } = await clientWith({ list_incidents: { body: { incidents: [] } } }, []);
    renderAt(api, "/incidents");
    await screen.findByText(/do not hold the agent_supervision capability/);
    expect(sent).toEqual([]);
  });

  // 503 is a state of the deployment with a named remedy, not a failure of the
  // request. Reporting it as an outage sends somebody to the wrong place.
  it("reports an unmigrated database as a deployment state", async () => {
    const { api } = await clientWith({
      list_incidents: {
        status: 503,
        body: { error: "the incident tables are not deployed in this database; run `update_db -migrateDb`" },
      },
    });
    renderAt(api, "/incidents");
    await screen.findByText("The incident tables are not installed in this database.");
    expect(screen.getByText(/update_db -migrateDb/)).toBeTruthy();
  });
});

describe("one incident", () => {
  it("renders the locus with what the record cannot see about it", async () => {
    const { api } = await clientWith({ get_incident: { body: disclosed } });
    renderAt(api, "/incidents/inc_1");
    await screen.findByRole("heading", { name: "inc_1" });
    // The gloss and the blind spot travel with the value. Without the second,
    // `worker_failed` is a word that looks like a diagnosis.
    expect(screen.getByText(/A worker reported failed/)).toBeTruthy();
    expect(screen.getByText(/comma join of up to eight feeders/)).toBeTruthy();
  });

  it("says an empty contradicting set is asserted rather than absent", async () => {
    const { api } = await clientWith({ get_incident: { body: disclosed } });
    renderAt(api, "/incidents/inc_1");
    await screen.findByRole("heading", { name: "inc_1" });
    expect(screen.getByText("None asserted.")).toBeTruthy();
    expect(screen.getByText("None cited.")).toBeTruthy();
  });

  // §B.3's escalation trigger, which the domain model states as a
  // rule-countable fact: contradicting evidence exceeding supporting.
  it("flags a hypothesis contradicted more than it is supported", async () => {
    const { api } = await clientWith({ get_incident: { body: disclosed } });
    renderAt(api, "/incidents/inc_1");
    await screen.findByRole("heading", { name: "inc_1" });
    expect(screen.getAllByText("contradicted more than supported").length).toBe(1);
  });

  // **A response carrying no `permittedTransitions` renders read-only**, which is
  // this screen's behaviour against a server predating `AJ.2` and is why the
  // fields are optional on the wire. It was the whole screen until 2026-09-05;
  // it is now the fallback, and the tests below are the control itself.
  it("offers no way to write when the server names no permitted transition", async () => {
    const { api, sent } = await clientWith({ get_incident: { body: disclosed } });
    renderAt(api, "/incidents/inc_1");
    await screen.findByRole("heading", { name: "inc_1" });
    const buttons = screen.getAllByRole("button").map((b) => b.textContent);
    expect(buttons).toEqual(["Refresh"]);
    await waitFor(() => expect(sent.length).toBe(1));
    expect(sent[0]?.["action"]).toBe("get_incident");
  });

  // AB.4, Q-32. The run reference is not provenance trivia: it is what decides
  // whether a correction to this incident reaches the audit hash chain, and a
  // supervision screen is the only place a person could learn that it will not.
  it("says an incident with no agent run has corrections that are not hash-chained", async () => {
    const { api } = await clientWith({ get_incident: { body: disclosed } });
    renderAt(api, "/incidents/inc_1");
    await screen.findByRole("heading", { name: "inc_1" });
    expect(screen.getByText("no agent run")).toBeTruthy();
    expect(screen.getByText(/not hash-chained/)).toBeTruthy();
  });

  it("names the run when one raised the incident, and says corrections chain to it", async () => {
    const { api } = await clientWith({
      get_incident: { body: { ...disclosed, incident: { ...detail, runRef: "run_abc" } } },
    });
    renderAt(api, "/incidents/inc_1");
    await screen.findByRole("heading", { name: "inc_1" });
    expect(screen.getByText("run_abc")).toBeTruthy();
    expect(screen.getByText(/appended to that run's audit chain/)).toBeTruthy();
  });

  // AE.2, I-311. The marker was read by nothing and this screen rendered the
  // field it marks to any holder of `agent_supervision`. Two assertions, because
  // they are two different claims: that the value does not arrive, and that the
  // reader is told why rather than shown a blank.
  it("renders a withheld PHI statement as words and names the capability", async () => {
    const redactedDetail = {
      ...detail,
      hypotheses: detail.hypotheses.map((h) => ({
        ...h,
        supportingEvidence: h.supportingEvidence.map((e) => ({
          ...e,
          statement: "",
          statementRedacted: true,
        })),
        contradictingEvidence: h.contradictingEvidence.map((e) => ({
          ...e,
          statement: "",
          statementRedacted: true,
        })),
      })),
    };
    const { api } = await clientWith({
      get_incident: { body: { ...disclosed, incident: redactedDetail, phiRedacted: true } },
    });
    renderAt(api, "/incidents/inc_1");
    await screen.findByRole("heading", { name: "inc_1" });
    expect(screen.queryByText("step 3 ran 4x longer")).toBeNull();
    expect(screen.getAllByText("statement withheld · PHI").length).toBe(2);
    expect(screen.getByText(/agent_phi_access/)).toBeTruthy();
    expect(screen.getByText(/withheld by the server, not hidden here/)).toBeTruthy();
  });

  // The other half of the same claim, and it is what makes the assertion above
  // about a control rather than about a stylesheet: with the capability the
  // statements are there and no banner is shown.
  it("shows the statements and no banner when PHI was disclosed", async () => {
    const { api } = await clientWith({ get_incident: { body: disclosed } });
    renderAt(api, "/incidents/inc_1");
    await screen.findByRole("heading", { name: "inc_1" });
    expect(screen.getByText("step 3 ran 4x longer")).toBeTruthy();
    expect(screen.queryByText(/withheld by the server/)).toBeNull();
  });

  it("distinguishes shard 0 from no shard", async () => {
    const { api } = await clientWith({ get_incident: { body: disclosed } });
    renderAt(api, "/incidents/inc_1");
    await screen.findByRole("heading", { name: "inc_1" });
    // shardRef 0 is a shard. A screen that treated it as falsy would report an
    // incident localised to the first shard as localised to none.
    expect(screen.queryByText("not localised to a shard")).toBeNull();
  });
});

/**
 * Criterion 50's fourth clause: *over an incident **triage** wrote* (task AC.3).
 *
 * **Every fixture above this line is hand-written, and that is what the clause
 * objects to.** A fixture its author agreed with by construction is I-147's
 * shape arriving at the wire: the stub is shaped like the caller, so it passes
 * whatever the caller does. `triagedRow` even carries `severity: "high"`, which
 * triage does not write — the shadow-mode writer supplies `info` for every
 * incident and argues for it from the deployment posture rather than from the
 * failure (I-306).
 *
 * The payload below is not written here. It is generated by
 * `TestTheScreensFixtureIsAnIncidentTriageWrote` in `jets/apiserver`, which runs
 * the classifier and the ranker over a real execution record against a real
 * PostgreSQL and projects the result through `get_incident` itself — so the
 * shape is the wire shape and the content is what triage concluded. That test
 * fails when the two stop agreeing, which is what makes this a guard rather than
 * a snapshot.
 *
 * **What it does not establish**: no browser has rendered this and no live
 * apiserver has served it. The distance between *the component renders under
 * jsdom* and *an operator read it* is the one criterion 31 spent two phases
 * crossing, and nothing here shortens it.
 */
describe("an incident triage actually wrote", () => {
  // The verdict control over the golden payload (`AJ.2`). **This is the one
  // assertion here that is not about rendering**: the buttons are whatever
  // `permittedTransitions` carries, and on a payload triage produced that is
  // exactly one, because the incident reached `diagnosed` and A.5 draws one edge
  // out of it. A fixture regenerated after a lifecycle change fails this rather
  // than quietly offering a different set.
  it("offers the transition A.5 draws out of the status triage left it in", async () => {
    const { api } = await clientWith({ get_incident: { body: triageWritten } });
    renderAt(api, `/incidents/${triageWritten.incident.incidentId}`);
    await screen.findByRole("heading", { name: triageWritten.incident.incidentId });
    expect(triageWritten.incident.status).toBe("diagnosed");
    const buttons = screen.getAllByRole("button").map((b) => b.textContent);
    expect(buttons).toEqual(["Refresh", "Remediation proposed"]);
    // `reclassified` is not among them, so no cause chooser is offered.
    expect(screen.queryByRole("combobox")).toBeNull();
  });

  it("renders its locus, its unclaimed cause and its ranked hypotheses", async () => {
    const written = triageWritten.incident;
    const { api } = await clientWith({
      get_incident: { body: triageWritten },
    });
    renderAt(api, `/incidents/${written.incidentId}`);
    await screen.findByRole("heading", { name: written.incidentId });

    // The two taxonomies, on a row nothing typed.
    expect(written.classification).toBe("");
    expect(screen.getByText("not claimed")).toBeTruthy();
    expect(screen.getAllByText(vocabLabel(written.locus)).length).toBeGreaterThan(0);
    // The blind spot travels with the locus — the half of the gate's reading a
    // summary drops.
    expect(screen.getByText(/Cannot see:/)).toBeTruthy();

    // Ranked, and both sides of every hypothesis are on the screen.
    expect(written.hypotheses.length).toBeGreaterThan(1);
    for (const h of written.hypotheses) {
      expect(screen.getByText(`#${h.rank}`)).toBeTruthy();
      expect(h.contradictingEvidence.length).toBeGreaterThan(0);
      for (const e of h.contradictingEvidence) {
        expect(screen.getByText(e.statement)).toBeTruthy();
      }
    }

    // Severity is a posture and not a measurement, and the row says `info`
    // rather than a judgement about how much this run matters (I-306).
    expect(written.severity).toBe("info");
  });

  // Criterion 45's last clause, on the screen. jetsapi.hypothesis has no basis
  // column and no locus column, so the ranker's account of what it considered
  // and dropped rides the `triaged -> diagnosed` transition. Without this
  // section the reasoning reaches the database and stops there.
  it("shows how it got here, and the ranker's own basis with it", async () => {
    const { api } = await clientWith({ get_incident: { body: triageWritten } });
    renderAt(api, `/incidents/${triageWritten.incident.incidentId}`);
    await screen.findByRole("heading", { name: "How this incident got here" });

    const transitions = triageWritten.transitions;
    expect(transitions.length).toBeGreaterThan(1);
    for (const t of transitions) {
      expect(t.actorKind).toBe("agent");
      expect(t.rationale).not.toBe("");
      expect(screen.getByText(t.rationale)).toBeTruthy();
    }
    // The system's own verdict on its own work is labelled as such, so a
    // supervisor is not left to infer it from an email address (I-292).
    expect(screen.getAllByText("the system itself").length).toBe(transitions.length);
    // And a transition on an incident nothing agentic raised is outside the
    // hash chain, which is the whole visible consequence of AB.4 (R-44).
    expect(screen.getAllByText("not hash-chained").length).toBe(transitions.length);
  });

  // The negative control for the section above, seen to fail before being
  // believed: a database migrated between AB.1 and AB.2 has the incident and no
  // history for it, and an empty list must read as a deployment state rather
  // than as a blank.
  it("says so when there is no transition history at all", async () => {
    const { api } = await clientWith({
      get_incident: { body: { ...triageWritten, transitions: [] } },
    });
    renderAt(api, `/incidents/${triageWritten.incident.incidentId}`);
    await screen.findByText(/No recorded transitions/);
  });
});

/**
 * The two columns Q-46 added at `AC.3`, answered by the user 2026-09-04 and
 * applied before the first row was written.
 *
 * **These assertions are over the generated payload rather than a fixture**, so
 * what they check is that the ranking's arithmetic reached the screen from a
 * real write and not that somebody typed three numbers that agree.
 */
describe("a hypothesis's own basis and locus", () => {
  it("shows the rank as arithmetic a reader can check against the lists below it", async () => {
    const { api } = await clientWith({ get_incident: { body: triageWritten } });
    renderAt(api, `/incidents/${triageWritten.incident.incidentId}`);
    await screen.findByRole("heading", { name: triageWritten.incident.incidentId });

    for (const h of triageWritten.incident.hypotheses) {
      // The counts are the lengths of the arrays the screen renders beside them.
      expect(h.basis.supportingCount).toBe(h.supportingEvidence.length);
      expect(h.basis.contradictingCount).toBe(h.contradictingEvidence.length);
      // And the confidence is that ratio, which is the whole reason the basis is
      // numbers: R-48 warns it will be read as a probability, and a reader who
      // can see both counts can see that it is not one.
      const total = h.basis.supportingCount + h.basis.contradictingCount;
      expect(h.confidence).toBeCloseTo(h.basis.supportingCount / total, 9);
      expect(
        screen.getByText(
          new RegExp(
            `Ranked on ${h.basis.supportingCount} for and ${h.basis.contradictingCount} against`,
          ),
        ),
      ).toBeTruthy();
    }
    expect(screen.getAllByText(/not a probability/).length).toBe(
      triageWritten.incident.hypotheses.length,
    );
  });

  // The reason `hypothesis_locus` is a column rather than a join. AC.2 measured
  // 20 of 29 model-generated hypotheses sitting at loci triage did not find
  // present; without the column such a row is indistinguishable on the screen
  // from a sound one.
  it("flags a hypothesis raised at a locus other than the incident's, and does not flag one that is not", async () => {
    const clean = await clientWith({ get_incident: { body: triageWritten } });
    renderAt(clean.api, `/incidents/${triageWritten.incident.incidentId}`);
    await screen.findByRole("heading", { name: triageWritten.incident.incidentId });
    for (const h of triageWritten.incident.hypotheses) {
      expect(h.locus).toBe(triageWritten.incident.locus);
    }
    expect(screen.queryByText(/not this incident's locus/)).toBeNull();
    cleanup();

    // The shadow writer cannot produce this row — a test asserts that one
    // package over — so it is scripted here, which is the only way to see the
    // rendering a model arm would need.
    const strayed = {
      ...triageWritten,
      incident: {
        ...triageWritten.incident,
        hypotheses: triageWritten.incident.hypotheses.map((h) => ({
          ...h,
          locus: "run_not_started",
        })),
      },
    };
    const { api } = await clientWith({ get_incident: { body: strayed } });
    renderAt(api, `/incidents/${triageWritten.incident.incidentId}`);
    await screen.findAllByText(/not this incident's locus/);
  });
});

/**
 * The verdict control (`AJ.2`, Q-52) — the single change that gives
 * `HumanVerdicts` a writer.
 *
 * **What is worth testing is again what it refuses**, and the refusals are not
 * the same as `AE.1`'s. The screen may not invent a transition the server did
 * not offer; it may not send a reclassification the CHECK would refuse; and it
 * may not send an actor or an actor kind at all, because a client that could
 * name its own kind could write itself into the labelled population.
 */
describe("the verdict control", () => {
  // `triaged` is the only status with three successors and all three are
  // adjudications, which is why P4 §10.7 calls this screen the labelling
  // instrument.
  const adjudicable = {
    ...disclosed,
    permittedTransitions: ["diagnosed", "reclassified", "suppressed_as_benign"],
    classifications: ["parse_failure", "transformation_defect"],
  };

  it("offers exactly the transitions the server named", async () => {
    const { api } = await clientWith({ get_incident: { body: adjudicable } });
    renderAt(api, "/incidents/inc_1");
    await screen.findByRole("heading", { name: "inc_1" });
    const buttons = screen.getAllByRole("button").map((b) => b.textContent);
    expect(buttons).toEqual([
      "Refresh",
      "Diagnosed",
      "Reclassified",
      "Suppressed as benign",
    ]);
  });

  it("sends no actor and no actor kind, and says who it was recorded as", async () => {
    const { api, sent } = await clientWith({
      get_incident: { body: adjudicable },
      record_incident_transition: {
        body: {
          incidentEventId: "ievt_1", incidentId: "inc_1",
          fromStatus: "triaged", toStatus: "suppressed_as_benign",
          actor: "supervisor@example.com", actorKind: "human",
          classificationBefore: "", classificationAfter: "",
          transitionedAt: "2026-09-05T12:00:00Z", runRef: "", auditSeq: 0,
          permittedTransitions: [],
        },
      },
    });
    renderAt(api, "/incidents/inc_1");
    await screen.findByRole("heading", { name: "inc_1" });
    fireEvent.click(screen.getByRole("button", { name: "Suppressed as benign" }));

    await waitFor(() => expect(sent.length).toBeGreaterThan(1));
    const write = sent.find((r) => r["action"] === "record_incident_transition");
    expect(write).toBeTruthy();
    expect(write?.["fromStatus"]).toBe("triaged");
    expect(write?.["toStatus"]).toBe("suppressed_as_benign");
    // The two the request must not carry.
    expect(write).not.toHaveProperty("actor");
    expect(write).not.toHaveProperty("actorKind");
    // And the confirmation names the kind the server chose, which is the only
    // place a supervisor learns their verdict was recorded as a human's.
    await waitFor(() =>
      expect(screen.getByTestId("banner").textContent).toMatch(
        /supervisor@example.com \(human\)/,
      ),
    );
  });

  // AB.4, R-44. Seq 0 is not a failure and must not read as one.
  it("says in words when a verdict is recorded and not hash-chained", async () => {
    const { api } = await clientWith({
      get_incident: { body: adjudicable },
      record_incident_transition: {
        body: {
          incidentEventId: "ievt_2", incidentId: "inc_1",
          fromStatus: "triaged", toStatus: "diagnosed",
          actor: "supervisor@example.com", actorKind: "human",
          classificationBefore: "", classificationAfter: "",
          transitionedAt: "2026-09-05T12:00:00Z", runRef: "", auditSeq: 0,
          permittedTransitions: ["remediation_proposed"],
        },
      },
    });
    renderAt(api, "/incidents/inc_1");
    await screen.findByRole("heading", { name: "inc_1" });
    fireEvent.click(screen.getByRole("button", { name: "Diagnosed" }));
    await waitFor(() =>
      expect(screen.getByTestId("banner").textContent).toMatch(/not hash-chained/),
    );
  });

  // `incident_event_reclassified_ck` refuses a reclassification carrying neither
  // a cause nor a reason. Disabling says so before the round trip; the CHECK is
  // still what enforces it.
  it("will not send a reclassification with no cause and no reason", async () => {
    const { api, sent } = await clientWith({ get_incident: { body: adjudicable } });
    renderAt(api, "/incidents/inc_1");
    await screen.findByRole("heading", { name: "inc_1" });
    const button = screen.getByRole("button", { name: "Reclassified" });
    expect(button.hasAttribute("disabled")).toBe(true);

    fireEvent.change(screen.getByRole("textbox"), { target: { value: "the message names a mapping error" } });
    expect(screen.getByRole("button", { name: "Reclassified" }).hasAttribute("disabled")).toBe(true);
    fireEvent.change(screen.getByRole("combobox"), { target: { value: "transformation_defect" } });
    expect(screen.getByRole("button", { name: "Reclassified" }).hasAttribute("disabled")).toBe(false);

    fireEvent.click(screen.getByRole("button", { name: "Reclassified" }));
    await waitFor(() => expect(sent.length).toBeGreaterThan(1));
    const write = sent.find((r) => r["action"] === "record_incident_transition");
    expect(write?.["classification"]).toBe("transformation_defect");
    expect(write?.["rationale"]).toBe("the message names a mapping error");
  });

  // The cause list is the server's, and the screen offers no other.
  it("offers only the causes the server sent", async () => {
    const { api } = await clientWith({ get_incident: { body: adjudicable } });
    renderAt(api, "/incidents/inc_1");
    await screen.findByRole("heading", { name: "inc_1" });
    const options = Array.from(screen.getByRole("combobox").querySelectorAll("option"))
      .map((o) => (o as HTMLOptionElement).value)
      .filter((v) => v !== "");
    expect(options).toEqual(["parse_failure", "transformation_defect"]);
  });

  // proposals.test.tsx's argument, a second time: two supervisors on one
  // incident is not an edge case, and the recovery is to re-read rather than to
  // offer a retry of a verdict that has been overtaken.
  it("re-reads on a 409 rather than reporting a failure to retry", async () => {
    let gets = 0;
    const { api } = await clientWith({
      get_incident: () => {
        gets += 1;
        return { body: adjudicable };
      },
      record_incident_transition: {
        status: 409,
        body: { error: "incident inc_1 is in \"diagnosed\", not \"triaged\"" },
      },
    });
    renderAt(api, "/incidents/inc_1");
    await screen.findByRole("heading", { name: "inc_1" });
    expect(gets).toBe(1);
    fireEvent.click(screen.getByRole("button", { name: "Diagnosed" }));
    await waitFor(() => expect(gets).toBe(2));
    await waitFor(() =>
      expect(screen.getByTestId("banner").textContent).toMatch(/has been re-read/),
    );
  });

  it("says a terminal incident admits no verdict", async () => {
    const { api } = await clientWith({
      get_incident: {
        body: {
          ...disclosed,
          incident: { ...detail, status: "closed" },
          permittedTransitions: [],
          classifications: ["parse_failure"],
        },
      },
    });
    renderAt(api, "/incidents/inc_1");
    await screen.findByRole("heading", { name: "inc_1" });
    expect(screen.getByText(/admits no further transition/)).toBeTruthy();
    expect(screen.queryByRole("combobox")).toBeNull();
  });
});
